pipeline {
  agent any
  
  stages {
    stage('Checkout') {
      steps {
        git 'https://github.com/kayanifaisal1/simple-java-maven-app.git'
      }
    }
    
    stage('Build') {
      steps {
        powershell 'mvn clean package'
      }
    }
    
    stage('Test') {
      steps {
        powershell 'mvn test'
      }
    }
    
    stage('Deliver') {
      steps {
        powershell './jenkins/scripts/deliver.sh'
      }
    }
  }
}
